app_projects/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from app_projects.views import *
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app_projects.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),
    url(r'^permission/$', permission ,name='permission'),
    url(r'^createuser/user$', createUser ,name='createUser'),
    url(r'^createuser/$', user ,name='user'),
) 

projects/urls.py
from django.conf.urls import patterns, url
from projects import views

urlpatterns = patterns('',
    url(r'^$', views.projectsInProgress, name='projectsInProgress'),
    url(r'^completed$', views.projectsCompleted, name='projectsCompleted'),
    url(r'^(?P<project_id>\d+)/$', views.tasks, name='tasks'),
    url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/$', views.taskCompleted, name='taskCompleted'),
    url(r'^(?P<project_id>\d+)/addtask$', views.addTask, name='addTask'),
    url(r'^addproject$', views.addProject, name='addProject'),
    url(r'^completed/(?P<project_id>\d+)/$', views.projectCompleted, name='projectCompleted'),
    url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/start$', views.start, name='start'),
    url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/pause$', views.pause, name='pause'),
)

projects/models.py
from django.db import models
import datetime

class Project(models.Model):
    name = models.CharField(max_length=120)
    start_date = models.DateField(auto_now_add=True, blank=True)
    end_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False, blank=True)
    
    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Task(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField(auto_now_add=True, blank=True)
    end_date = models.DateField(blank=True, null=True)
    hours_worked = models.IntegerField(default='0',blank=True)
    project = models.ForeignKey(Project)

    def __unicode__(self):
        return self.name
 
    class Meta:
        ordering = ['start_date']

class Counter(models.Model):
    start = models.DateTimeField(null=True,blank=True)
    pause = models.DateTimeField(null=True,blank=True)
    task = models.ForeignKey(Task)
    """docstring for Counter"""
 #   def __unicode__(self):
 #      self
    def hours(self):
        duration = (self.pause - self.start)
        days, seconds = duration.days, duration.seconds
        minutes = (days*24*60) + (seconds%60)
        return minutes

    class Meta:
        ordering = ['pause']

app_projects/views.py
from django.contrib.auth.models import User
from django.shortcuts import render 
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def user(request):
	return render(request,'createUser.html')

def createUser(request):
	username = request.POST['username']
	password = request.POST['password']
	email = request.POST['email']
	user = User.objects.create_user(username, email, password)	
	user.save()
	return HttpResponseRedirect(reverse('django.contrib.auth.views.logout'))

def permission(request):
	return render(request,'permission.html')

projects/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse,  HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime
from django.contrib.auth.decorators import permission_required
from projects.models import Project, Task, Counter
from django.utils.timezone import utc


# Create your views here.
def projectsInProgress(request):
    projects = Project.objects.all() 
    project_list = []
    for project in projects:
    	if not project.completed:
    		project_list.append(project)
    return render(request, 'projectsProgress.html', {'project_list': project_list})

def projectsCompleted(request):
    projects = Project.objects.all() 
    project_list = []
    for project in projects:
    	if  project.completed:
    		project_list.append(project)
    return render(request, 'projectsCompleted.html', {'project_list': project_list})

@permission_required('projects.addproject')
def addProject(request):
	project = Project(name=request.POST["addproject"])
	project.save()
	return HttpResponseRedirect(reverse('projects:projectsInProgress'))

def taskCompleted(request, project_id, task_id):
	task = get_object_or_404(Task, id=task_id)
	task.end_date = datetime.date.today()
	task.save()
	return HttpResponseRedirect(reverse('projects:tasks', args=(project_id,)))

def projectCompleted(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	project.end_date = datetime.date.today()
	project.completed = True
	project.save()
	return HttpResponseRedirect(reverse('projects:projectsInProgress'))

def tasks(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    tasks = Task.objects.filter(project=project)
    return render(request, 'tasks.html', {'project': project, 'tasks':tasks})

def addTask(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	project.task_set.create(name=request.POST["addtask"])
	return HttpResponseRedirect(reverse('projects:tasks', args=(project_id,)))

def start(request, project_id, task_id):
	task = get_object_or_404(Task, id=task_id)
	list_counter = Counter.objects.filter(task=task_id)
	if len(list_counter) != 0:
		last = list_counter[len(list_counter)-1]
		if last.pause :
			counter = task.counter_set.create(start = datetime.datetime.utcnow().replace(tzinfo=utc))
	else:
		counter = task.counter_set.create(start = datetime.datetime.utcnow().replace(tzinfo=utc))
	return HttpResponseRedirect(reverse('projects:tasks', args=(project_id,)))

def pause(request, project_id, task_id):
	task = get_object_or_404(Task, id=task_id)
	list_counter = Counter.objects.filter(task=task_id)
	if  len(list_counter) != 0:
		last = list_counter[len(list_counter)-1]
		if not last.pause:
			last.pause = datetime.datetime.utcnow().replace(tzinfo=utc)
			last.save()
			duration = last.pause - last.start
			days, seconds = duration.days, duration.seconds
			minutes = (days*24*60) + (seconds/60)
			task.hours_worked = task.hours_worked + minutes
			task.save()
	return HttpResponseRedirect(reverse('projects:tasks', args=(project_id,)))

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="/static/bootstrap2/css/bootstrap.css" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>   
  </head>

  <body>
    <div class="container">
      <div class="row-fluid span12" >
          <div class="page-header">
            <h1>Projects</h1>      
          </div>
            <div class="pull-right">
                <p><a href="{% url 'user' %}">create user</a></p>
                {{ user }}
                {% if user.is_anonymous %}
                <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
                {% else %}
                <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
                {% endif %}
            </div>
          <nav class="navbar navbar-inner">
            <ul class="nav">
              {% block nav %}{% endblock %}
            </ul>
          </nav>
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>
    </div>
  <script src="/static/bootstrap/js/bootstrap.js"></script>   
  </body>
</html>

projects/templates/createUser.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="{% url 'createUser' %}">
{% csrf_token %}
	
	<legend>Create User</legend>

		<p>
		<label for="id_username">Username:</label>
		<input id="id_username" maxlength="254" name="username" type="text" >
		</p>

		<p>
		<label for="id_password">Password:</label>
		<input id="id_password" name="password" type="password">
		</p>

		<p>
		<label for="id_email">E-mail:</label>
		<input id="id_email" name="email" type="email">
		</p>

		<input class="btn" type="submit" value="login" />
		<input type="hidden" name="next" value="{{ next }}" />	
	
</form>

{% endblock %}

projects/templates/permission.html
{% extends "base.html" %}	

	{% block nav %}
          <li class="active span4"><a href="{%url 'projects:projectsInProgress'%}" class="brand">Projects in progress</a></li>
          <li class="span4"><a href="{%url 'projects:projectsCompleted'%}" class="brand">Projects completed</a></li>
	{% endblock %}	
			
	{% block content %}
		<p>You don't have permissions to add projects in the application.</p>
	{% endblock %}

projects/templates/projectsCompleted.html
{% extends "base.html" %}	

	{% block nav %}
          <li class="span4"><a href="{%url 'projects:projectsInProgress'%}" class="brand">Projects in progress</a></li>
          <li class="active span4"><a href="{%url 'projects:projectsCompleted'%}" class="brand">   Projects    completed</a></li>
	{% endblock %}	

	{% block content %}
		<div class="row-fluid span12">
			<table class="table table-bordered table-striped table-hover">
				<tr >
					<th class="span5">Name</th>
					<th class="span5">Start Date</th>
					<th class="span5">Completed</th>
				</tr>
			{% for project in project_list %}
				<tr>			
					<td class="span5"><a href="{% url 'projects:tasks' project.id %}">{{project.name}}</a></td>
					<td class="span5">{{project.start_date}}</td>
					<td>{{project.end_date}}</td>
					<td class="span5">{{project.completed}}</td>			
				</tr>
			{% endfor %}
			</table>
		</div>
	{% endblock %}	

projects/templates/projectsProgress.html
{% extends "base.html" %}	

	{% block nav %}
          <li class="active span4"><a href="{%url 'projects:projectsInProgress'%}" class="brand">Projects in progress</a></li>
          <li class="span4"><a href="{%url 'projects:projectsCompleted'%}" class="brand">Projects completed</a></li>
	{% endblock %}	
			
	{% block content %}
		<div class="row-fluid span12">
			<table class="table table-bordered table-striped table-hover span8">
				<tr >
					<th class="span5">Name</th>
					<th class="span5">Start Date</th>
					<th class="span5">Completed</th>
				</tr>
			{% for project in project_list %}
				<tr>			
					<td class="span5"><a href="{% url 'projects:tasks' project.id %}">{{project.name}}</a></td>
					<td class="span5">{{project.start_date}}</td>
					<td class="span5">{{project.completed}}</td>			
				</tr>
			{% endfor %}
			</table>
			</br>
			</br>
			{% if perms.projects.addproject %}
			{% for project in project_list %}
					<form action="{% url 'projects:projectCompleted' project.id %}" >	
					{% csrf_token %}
							<button type="submit" class="btn span3" id="{{project.id}}">completed</button>
					</form>
			{% endfor %}
			{% else %}
    	   	<p>You don't have permissions to completed projects in the application.</p>
    	{% endif %}
		</div>

		
		<form action="{%url 'projects:addProject' %}" class="span6" method="post">
		{% csrf_token %}
			<legend>Add Project</legend>
			<div class="input-append">
				<label for="add">Name</label><input for="add"  type="text" name="addproject" required="required">
				<input type="submit" class="btn" value="Add">  
			</div>	
		</form>
		
	{% endblock %}

projects/templates/startTask.html
		{% for task in tasks %}
			{% if not task.end_date %}
				<div class="btn-group span3">
					<form action="{%url 'projects:start' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">start</button>
					</form>
					<form action="{%url 'projects:pause' project.id task.id counter.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">pause</button>	
					</form>	
				</div>
				<form action="{%url 'projects:taskCompleted' project.id task.id %}" class="" method="post">
				{% csrf_token %}
				<button type="submit" class="btn span2">completed</button>
				</form>
			{% else %}
				<div class="btn-group span3">
					<form action="{%url 'projects:start' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn" disabled="disabled">start</button>
					</form>
					<form action="{%url 'projects:pause' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn" disabled="disabled">pause</button>	
					</form>	
				</div>
				<form action="{%url 'projects:taskCompleted' project.id task.id%}" class="" method="post">
				{% csrf_token %}
				<button type="submit" class="btn span2" disabled="disabled">completed</button>
				</form>
			{% endif %}
		{% endfor %}	

projects/templates/tasks.html
{% extends "base.html" %}		
			
	{% block nav %}
          <li class="active span4"><a href="{%url 'projects:projectsInProgress'%}" class="brand">Projects in progress</a></li>
          <li class="span4"><a href="{%url 'projects:projectsCompleted'%}" class="brand">Projects completed</a></li>
	{% endblock %}	

	{% block content %}
	
	<div class="row-fluid span12">
		<h2>{{project.name}}</h2>
		<table class="table table-bordered table-striped table-hover span6">
			<tr>
				<th class="span3">Name</th>
				<th class="span3">Start Date</th>
				<th class="span3">End Date</th>
				<th class="span3">Minutes</th>
			</tr>
		{% for task in tasks %}
			<tr >
				<td class="span3">{{task.name}}</td>
				<td class="span3">{{task.start_date}}</td>
				<td class="span3">{{task.end_date}}</td>
				<td class="span3">{{task.hours_worked}}</td>	
			</tr>
		{% endfor %}
		</table>
		</br>
		</br>
		{% for task in tasks %}
			{% if not task.end_date %}
				<div class="btn-group span3">
					<form action="{%url 'projects:start' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">start</button>
					</form>
					<form action="{%url 'projects:pause' project.id task.id  %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">pause</button>	
					</form>	
				</div>
				<form action="{%url 'projects:taskCompleted' project.id task.id %}" class="" method="post">
				{% csrf_token %}
				<button type="submit" class="btn span2">completed</button>
				</form>
			{% else %}
				<div class="btn-group span3">
					<form action="{%url 'projects:start' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn" disabled="disabled">start</button>
					</form>
					<form action="{%url 'projects:pause' project.id task.id %}" class="span3" method="post">
					{% csrf_token %}
					<button type="submit" class="btn" disabled="disabled">pause</button>	
					</form>	
				</div>
				<form action="{%url 'projects:taskCompleted' project.id task.id%}" class="" method="post">
				{% csrf_token %}
				<button type="submit" class="btn span2" disabled="disabled">completed</button>
				</form>
			{% endif %}
		{% endfor %}	
	</div>

	<form action="{%url 'projects:addTask' project.id %}" class="span6" method="post">
	{% csrf_token %}
		<legend>Add Task</legend>
		<div class="input-append">
			<label for="add">Name</label><input id="add"  type="text" name="addtask" required="required">
			<input type="submit" class="btn" value="Add">  
		</div>	
	</form>
	<h1>{{prueba.name}}</h1>
	{% endblock %}

projects/templates/user.html
{% block content %}
<p>User created with username: {{user.name}} and e-mail: {{user.emaill}}</p>
{% endblock %}